[tool.poetry]
name = "qmk_dead10ck"
version = "1.0.0"
description = "qmk"
authors = ["me"]

[tool.poetry.dependencies]
python = "^3.10"
qmk = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
